# Generated by Django 4.2.24 on 2025-12-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courriers', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_extrait', models.TextField(blank=True, null=True)),
                ('fiabilite', models.FloatField(default=0.0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('categorie_predite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('courrier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ia_result', to='courriers.courrier')),
                ('service_suggere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'verbose_name': 'Résultat IA',
                'verbose_name_plural': 'Résultats IA',
                'db_table': 'ia_result',
            },
        ),
    ]
