# Generated by Django 5.2.7 on 2025-12-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('courriers', '0004_modelecourrier_courrier_barcode_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='actions_requises',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='delai_attente_max',
            field=models.IntegerField(default=48),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='heures_avant_notification',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='notifier_avant_expiration',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Accuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_accuse', models.CharField(choices=[('reception', 'Accusé de réception'), ('imputation', "Accusé d'imputation"), ('traitement', 'Accusé de traitement')], max_length=20)),
                ('destinataire_email', models.EmailField(max_length=254)),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='envoye', max_length=20)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuses', to='courriers.courrier')),
            ],
            options={
                'db_table': 'courrier_accuse',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_courrier', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant'), ('interne', 'Interne')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'db_table': 'workflow_template',
            },
        ),
    ]
