# Generated by Django 4.2.24 on 2025-12-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='classificationrule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['keyword'], name='core_classi_keyword_e53f19_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationrule',
            index=models.Index(fields=['priority'], name='core_classi_priorit_9916b7_idx'),
        ),
    ]
