# Generated by Django 5.2 on 2025-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rapport statistique',
                'verbose_name_plural': 'Rapports statistiques',
                'db_table': 'dashboard_rapport',
                'ordering': ['-created_at'],
            },
        ),
    ]
