# Generated by Django 4.2.24 on 2025-12-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('anciens_valeurs', models.TextField(blank=True, null=True)),
                ('nouvelles_valeurs', models.TextField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique action',
                'verbose_name_plural': 'Historique actions',
                'db_table': 'courrier_historique',
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant'), ('interne', 'Interne')], default='entrant', max_length=20)),
                ('objet', models.CharField(max_length=500)),
                ('contenu_texte', models.TextField(blank=True, null=True)),
                ('confidentialite', models.CharField(default='normal', max_length=30)),
                ('expediteur_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('expediteur_adresse', models.TextField(blank=True, null=True)),
                ('expediteur_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destinataire_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('canal', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('impute', 'Imputé'), ('traitement', 'En traitement'), ('repondu', 'Répondu'), ('archive', 'Archivé')], default='recu', max_length=30)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_envoi', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_archivage', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'db_table': 'courrier_courrier',
            },
        ),
        migrations.CreateModel(
            name='Imputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('suggestion_ia', models.BooleanField(default=False)),
                ('score_ia', models.FloatField(blank=True, null=True)),
                ('date_imputation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imputation',
                'verbose_name_plural': 'Imputations',
                'db_table': 'courrier_imputation',
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='courriers/pieces/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='courriers.courrier')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'db_table': 'courrier_piecejointe',
            },
        ),
    ]
