# Generated by Django 4.2.24 on 2025-12-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courriers', '0001_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejointe',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imputation',
            name='courrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='courriers.courrier'),
        ),
        migrations.AddField(
            model_name='imputation',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imputation',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrier',
            name='service_impute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
        migrations.AddField(
            model_name='actionhistorique',
            name='courrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='courriers.courrier'),
        ),
        migrations.AddField(
            model_name='actionhistorique',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['reference'], name='courrier_co_referen_04d977_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['statut'], name='courrier_co_statut_d9ac49_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['created_at'], name='courrier_co_created_fef719_idx'),
        ),
    ]
