# Generated by Django 5.2.7 on 2025-12-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0002_add_priority_field'),
        ('courriers', '0002_initial'),
    ]

    operations = [
    ]
