# Generated by Django 5.2.7 on 2025-12-30 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('courriers', '0003_merge_0002_add_priority_field_0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_modele', models.CharField(choices=[('entrant', 'Réponse à courrier entrant'), ('sortant', 'Courrier sortant standard'), ('interne', 'Note interne')], max_length=20)),
                ('contenu', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('entete', models.TextField(blank=True, null=True)),
                ('pied_page', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courrier_modele',
            },
        ),
        migrations.AddField(
            model_name='courrier',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_limite_traitement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='responsable_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_encours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courrier',
            name='service_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_actuels', to='core.service'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='canal',
            field=models.CharField(choices=[('physique', 'Physique'), ('email', 'Email'), ('portail', 'Portail'), ('autre', 'Autre')], default='physique', max_length=20),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='confidentialite',
            field=models.CharField(choices=[('normale', 'Normale'), ('restreinte', 'Restreinte'), ('confidentielle', 'Confidentielle')], default='normale', max_length=20),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='type',
            field=models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant'), ('interne', 'Interne')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['priorite'], name='courrier_co_priorit_1d4b0e_idx'),
        ),
        migrations.AddField(
            model_name='modelecourrier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='modelecourrier',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
    ]
