# Generated by Django 5.2.7 on 2025-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0004_modelecourrier_courrier_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='meta_analyse',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='reponse_suggeree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
