# Generated by Django 5.2.7 on 2026-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0005_courrier_meta_analyse_courrier_reponse_suggeree'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='expediteur_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
